'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh';

interface Translations {
    [key: string]: {
        en: string;
        zh: string;
    };
}

const translations: Translations = {
    // Navigation
    appName: { en: 'PixelMentor', zh: 'PixelMentor' },
    login: { en: 'Log in', zh: '登录' },
    signup: { en: 'Sign up free', zh: '免费注册' },
    upload: { en: 'Upload', zh: '上传照片' },
    history: { en: 'History', zh: '历史记录' },
    logout: { en: 'Log out', zh: '登出' },
    tryItOut: { en: 'Try it out', zh: '直接试用' },
    guestMode: { en: 'Guest Mode', zh: '游客模式' },
    loginPrompt: { en: 'Login / Register', zh: '登录 / 注册' },

    // Landing Page
    heroTitle1: { en: 'Elevate Your Photos with', zh: '让您的照片焕发新生' },
    heroTitle2: { en: 'Advanced AI Vision', zh: '高级 AI 视觉分析' },
    heroDesc: {
        en: 'Upload your images and let our advanced AI vision model analyze them and provide professional post-processing suggestions to make your shots truly stunning.',
        zh: '上传您的图片，让先进的 AI 视觉模型对其进行分析，并提供专业的后期修图建议，让您的摄影作品真正令人惊艳。'
    },
    getStarted: { en: 'Get Started Now', zh: '立即开始' },

    // Auth pages
    welcomeBack: { en: 'Welcome Back', zh: '欢迎回来' },
    loginDesc: { en: 'Log in to your account', zh: '登录您的账户' },
    email: { en: 'Email Address', zh: '邮箱地址' },
    password: { en: 'Password', zh: '密码' },
    loggingIn: { en: 'Logging in...', zh: '登录中...' },
    noAccount: { en: "Don't have an account?", zh: '还没有账户？' },

    createAccount: { en: 'Create Account', zh: '创建账户' },
    joinToday: { en: 'Join today', zh: '立即加入' },
    fullName: { en: 'Full Name', zh: '全名' },
    creatingAccount: { en: 'Creating account...', zh: '创建账户中...' },
    hasAccount: { en: 'Already have an account?', zh: '已有账户？' },

    // Dashboard
    uploadTitle: { en: 'Upload Photo for', zh: '上传照片进行' },
    uploadTitleHighlight: { en: 'Analysis', zh: '智能分析' },
    uploadDesc: { en: 'Get professional AI-driven post-processing suggestions', zh: '获取专业的 AI 驱动后期修图建议' },
    clickToUpload: { en: 'Click to select an image', zh: '点击选择图片' },
    analyzeBtn: { en: 'Analyze Photo', zh: '分析照片' },
    analyzingBtn: { en: 'Analyzing with AI...', zh: 'AI 正在分析...' },
    analysisResultTitle: { en: 'Analysis Result', zh: '分析结果' },
    aiThinking: { en: 'AI is thinking...', zh: 'AI 正在思考...' },
    uploadPromptText: { en: 'Upload an image to see suggestions here.', zh: '上传图片即可在此查看专业建议。' },

    // History
    historyTitle: { en: 'Your Analysis History', zh: '您的历史分析记录' },
    loadingHistory: { en: 'Loading history...', zh: '加载记录中...' },
    noHistory: { en: "You haven't analyzed any photos yet.", zh: '您还没有分析过任何照片。' },

    // AI Prompt (Hidden from UI, sent to API)
    defaultPrompt: {
        en: 'Analyze the content of this photo and provide detailed post-processing suggestions, breaking it down into specific areas like Color, Lighting, and Composition. Use markdown format. Use ## Headings for categories, bullet points for items, and wrap key specific adjustments or numeric parameters in **bold** to make it very easy to read and beautiful. Respond in English.',
        zh: '请分析这张照片的内容，并提供专业的后期修图建议。请将建议划分为具体的维度（如：色彩调整、光影细节、构图裁剪等）。请务必使用 Markdown 格式排版，使用 ## 二级标题分类，使用列表，并将需要调整的具体参数或核心关键词用 **加粗字体** 突出显示，使得排版美观、重点清晰。请用中文回复。'
    },

    // Disclaimer
    aiDisclaimer: {
        en: 'Content generated by AI, for reference only.',
        zh: '内容由AI生成，仅供参考'
    }
};

interface LanguageContextType {
    lang: Language;
    toggleLang: () => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [lang, setLang] = useState<Language>('zh');

    useEffect(() => {
        const saved = localStorage.getItem('appLang') as Language;
        if (saved) setLang(saved);
    }, []);

    const toggleLang = () => {
        const newLang = lang === 'en' ? 'zh' : 'en';
        setLang(newLang);
        localStorage.setItem('appLang', newLang);
    };

    const t = (key: string) => {
        return translations[key]?.[lang] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
